from my_project.auth.domain.orders.aircraft import Aircraft
from my_project.auth.domain.orders.airline import Airline
from my_project.auth.domain.orders.airport import Airport
from my_project.auth.domain.orders.crew import Crew
from my_project.auth.domain.orders.flight import Flight
from my_project.auth.domain.orders.flighthistory import FlightHistory
from my_project.auth.domain.orders.maintenance import Maintenance
from my_project.auth.domain.orders.pilot import Pilot
from my_project.auth.domain.orders.registration import Registration
from my_project.auth.domain.orders.route import Route
from my_project.auth.domain.orders.airline_airport import AirlineAirport
